### ISSUE TITLE
[regression?] Code folding gutter disappeared?

### ISSUE THREAD

**Issue by norru** [eclipse-corrosion/corrosion#137]
Hi,

I'm running latest snapshot of Eclipse 2018-09, tm4e, lsp4e and corrosion to test progress (a life on the edge, I know!).

After an "upgrade all", the code folding feature, which was working on the previous update, has disappeared again.

**Comment by norru** [comment]
Oddly, I don't think that the "update all" had anyting new from Corrosion snaps or tm4e itself, so there must be some sort of API oddity after upgrading the platform.

**Comment by norru** [comment]
This is low priority for me.

**Comment by norru** [comment]
@mickaelistria the code folding functionality disappeared a while ago after a short stint of actually working fine.
Is it something that would be addressed in 2018-12?

**Comment by mickaelistria** [comment]
I don't know what caused this to disappear, I don't even know which component was providing the functionality. As 2018-12 was released some time ago, it's definitely not addressed if you're still seeing the issue.
I personally cannot place this issue high in my priority todo-list, it's very unlikely I work on it soon (or even any time). You'll need to have a look at this issue or to recruit someone else to do it. Good luck!

**Comment by norru** [comment]
I thought it might be a case of configuring the TM4E plugin "descriptor". It's too low priority for me to worry, thanks anyway :)

**Comment by norru** [comment]
@angelozerr do you have any advice? How do we enable the folding gutter in our `plugin.xml`?

**Comment by norru** [comment]
> Code folding is managed by the language server. Perhaps it's an issue from LSP4E?

I think LSP4E assumes TM4E manages code folding. @mickaelistria ?

**Comment by mickaelistria** [comment]
> I think LSP4E assumes TM4E manages code folding. @mickaelistria ?

LSP4E doesn't know nor assume anything about TM4E. If documentFolding is supported by LSP, it should be supported by LSP4E and work for any LS that provides folding.

**Comment by angelozerr** [comment]
> I don't know what caused this to disappear, I don't even know which component was providing the functionality.

The first step to do is to debug 
https://git.eclipse.org/c/lsp4e/lsp4e.git/tree/org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/folding/LSPFoldingReconcilingStrategy.java

**Comment by norru** [comment]
>  If documentFolding is supported by LSP, it should be supported by LSP4E and work for any LS that provides folding

I've left the VSCode guys a comment asking for pointers - see if something bites.

**Comment by norru** [comment]
I've done a quick check and I could not find any instances of `foldingRange` in my RLS logs.

It kind of confirms that RLS doesn't implement it yet.

**Comment by norru** [comment]
For reference https://bugs.eclipse.org/bugs/show_bug.cgi?id=537706

**Comment by norru** [comment]
> The best mean is to improve this condition with org.eclipse.lsp4e.cansSupportFolding

@angelozerr Does this property need to be implemented?

**Comment by angelozerr** [comment]
> @angelozerr Does this property need to be implemented?

Yes, but it's hard I think since we cannot start the server when editor is created (I had tried it, but I failed it). Any PR ar ewelcome!

**Comment by norru** [comment]
Could not we find a way to let LS-specific plugins decide in a static way via `plugin.xml`?

**Comment by mickaelistria** [comment]
@norru Is this still an issue with 2019-06 RC2 ?

**Comment by norru** [comment]
I have tried on 2019-06 RC1 as it's what the IDE thinks it's latest. and it is still the case. Is RC2 not on the /updates Eclipse repository?

**Comment by norru** [comment]
Still open in Version: 2019-06 (4.12.0) Build id: 20190614-1200

**Comment by mickaelistria** [comment]
Could it be caused by https://bugs.eclipse.org/bugs/show_bug.cgi?id=547879 ?

**Comment by cplir-c** [comment]
Code folding is still not showing up in my eclipse version 4.20.0.v20210611-1600 installation with corrosion v1.2.1.202106081156. Should I open a new issue?

**Comment by akurtakov** [comment]
Do you still face the issue with latest version?

**Comment by norru** [comment]
Looks fixed.
