### ISSUE TITLE
What's the state of this project?

### ISSUE THREAD

**Issue by hydra** [eclipse-corrosion/corrosion#416]
I see there's been no updates on this repo since September 27th 2022, it's now 8th February 2023, I'm just wondering if this project is dead, needs new maintainers, etc?

Given that Rust is one of the most loved programming language (https://survey.stackoverflow.co/2022/#technology-most-loved-dreaded-and-wanted) and that Eclipse is the best free IDE with good embedded debugging support, it'd be really nice if Eclipse Corrosion was more frequently updated to fix outstanding issues.

On a day-to-day basis the main issues for me are the non-functioning outline and hover-over functionality due to Language Server Background job never completes, see https://github.com/rust-lang/rust-analyzer/issues/10910#issuecomment-1422332052

**Comment by akurtakov** [comment]
The projects definetely need new blood. People that created it initially mostly moved on to other duties so not many updates are to be expected unless someone jumps in to take over maintenance. Considering that majority of the functionality is provided by other Eclipse bits which are still well maintained this shouldn't be too much effort for someone using Rust daily so can help on rust-analyzer side.

**Comment by norru** [comment]
It's a bit stale to be fair, unfortunately I haven't had much time to contribute.

On a good note, I did get the up-to date version from `snapshots` today, on top of an up-to-date Eclipse and it doesn't seem to have rotten away (and it's happily working with my old Rust projects).

I've been using JetBrains CLion on and off for Rust development too, lately. It's a polished experience but the lack of support for Rust-analyser and full-solution analysis is really upsetting. Their replacement for it, called "Inspections" are between unusable and counterproductive.
