### ISSUE TITLE
Builds for 2024-9 R

### ISSUE THREAD

**Issue by fithisux** [eclipse-corrosion/corrosion#442]
Are they on the horizon?

**Comment by akurtakov** [comment]
snapshot builds are done against 2024-9 please try them https://download.eclipse.org/corrosion/snapshots/ . If you ask for a release we haven't planned any for now yet.
Do you face any issue/incompatibility with latest release?

**Comment by fithisux** [comment]
I will report back tomorrow.

**Comment by fithisux** [comment]
The installation worked without issues.

**Comment by akurtakov** [comment]
I hope you can use it proper. I have quite some issues under Linux. Closing this one.
